"""add uri column

Revision ID: cdd8585b0bc7
Revises: 1bcd60ce3327
Create Date: 2022-06-16 05:35:34.188082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd8585b0bc7'
down_revision = '1bcd60ce3327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('uri', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'uri')
    # ### end Alembic commands ###
