"""Add spotify id column to User model

Revision ID: 1bcd60ce3327
Revises: 983f93957798
Create Date: 2022-06-15 20:35:27.380729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcd60ce3327'
down_revision = '983f93957798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_id')
    # ### end Alembic commands ###
