"""Delete playlists_songs and playlists tables

Revision ID: 1cc45793d24e
Revises: cdd8585b0bc7
Create Date: 2022-06-23 22:46:32.294922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1cc45793d24e"
down_revision = "cdd8585b0bc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlists_songs")
    op.drop_table("playlists")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists_songs",
        sa.Column(
            "playlist_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("song_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name="playlists_songs_playlist_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
            name="playlists_songs_song_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("playlist_id", "song_id", name="playlists_songs_pkey"),
    )
    op.create_table(
        "playlists",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="playlists_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="playlists_pkey"),
    )
    # ### end Alembic commands ###
